### ISSUE TITLE
Problems with running eval.py

### ISSUE THREAD

**Issue by ran894694447** [dornik/sporeagent#1]
Thank you for this great work. When I run `python registration/eval.py--dataset=lm`, it pops up to report an error:
```
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[w] b'The GLFW library is not initialized'
[x] Window creation failed
```
What can I do about it?Looking forward to your reply! Thank you!

**Comment by ran894694447** [comment]
I solved the problem by commenting out 

>  https://github.com/dornik/sporeagent/blob/a95139c47534670f7a47f86adf62d3e488981409/environment/renderer.py#L83
but a new problem appears:` OpenGL.error.NullFunctionError: Attempt to call an undefined function glGenFramebuffers, check for bool( NullFunctionError: Attempt to call an undefined function glGenFramebuffers, check for bool( glGenFramebuffers) before calling. `
How can I solve this?

**Comment by dornik** [comment]
The `app.Window` here provides you with a valid GL context. That's why, after commenting this line, you are no longer able to make calls to OpenGL functions (such as `glGenFramebuffers`). You can check the [`glumpy` tutorial](https://glumpy.readthedocs.io/en/latest/tutorial/introduction.html) for an introduction to these concepts. Also check-out their _Getting started_ section to see if you can run the basic examples in your current python environment.

Now for your original error message, there are multiple reasons for what might have gone wrong there. Assuming that you're running Linux, here are a few:

- access to your GPU? run `glxinfo` and check if `direct rendering` is available
- backend available? check if `glfw3` installed (as we specifically request that in line 5 of `renderer.py`)
- running in a container/remotely? you might need X11 forwarding to be able to get a window handle

Hope this helps!

**Comment by ran894694447** [comment]
> The `app.Window` here provides you with a valid GL context. That's why, after commenting this line, you are no longer able to make calls to OpenGL functions (such as `glGenFramebuffers`). You can check the [`glumpy` tutorial](https://glumpy.readthedocs.io/en/latest/tutorial/introduction.html) for an introduction to these concepts. Also check-out their _Getting started_ section to see if you can run the basic examples in your current python environment.
> 
> Now for your original error message, there are multiple reasons for what might have gone wrong there. Assuming that you're running Linux, here are a few:
> 
> * access to your GPU? run `glxinfo` and check if `direct rendering` is available
> * backend available? check if `glfw3` installed (as we specifically request that in line 5 of `renderer.py`)
> * running in a container/remotely? you might need X11 forwarding to be able to get a window handle
> 
> Hope this helps!

Thanks for the reply, I will try it.

**Comment by ran894694447** [comment]
> The `app.Window` here provides you with a valid GL context. That's why, after commenting this line, you are no longer able to make calls to OpenGL functions (such as `glGenFramebuffers`). You can check the [`glumpy` tutorial](https://glumpy.readthedocs.io/en/latest/tutorial/introduction.html) for an introduction to these concepts. Also check-out their _Getting started_ section to see if you can run the basic examples in your current python environment.
> 
> Now for your original error message, there are multiple reasons for what might have gone wrong there. Assuming that you're running Linux, here are a few:
> 
> * access to your GPU? run `glxinfo` and check if `direct rendering` is available
> * backend available? check if `glfw3` installed (as we specifically request that in line 5 of `renderer.py`)
> * running in a container/remotely? you might need X11 forwarding to be able to get a window handle
> 
> Hope this helps!

@dornik I checked it after following your reply and there is nothing wrong in that regard. But still encountered a new problem:
```
Traceback (most recent call last):
  File "registration/eval.py", line 242, in <module>
    evaluate(agent, test_loader, args.dataset, bop_results_path)
  File "registration/eval.py", line 162, in evaluate
    use_normals=cfg.USE_NORMALS)  # lamp model (id 14) is single-sided
  File "/home/jiangfan/sporeagent/environment/renderer.py", line 203, in compute_score
    self.fbo_stage_1.activate()
  File "/home/jiangfan/anaconda3/envs/sporeagent/lib/python3.6/site-packages/glumpy/gloo/globject.py", line 95, in activate
    self._activate()
  File "/home/jiangfan/anaconda3/envs/sporeagent/lib/python3.6/site-packages/glumpy/gloo/framebuffer.py", line 378, in _activate
    self._attach()
  File "/home/jiangfan/anaconda3/envs/sporeagent/lib/python3.6/site-packages/glumpy/gloo/framebuffer.py", line 434, in _attach
    raise RuntimeError('Combination of internal formats used '
RuntimeError: Combination of internal formats used by attachments is not supported.

```
The error message indicates that there was a problem activating the framebuffer. How can I solve this?

**Comment by ran894694447** [comment]
@dornik Hello, I have resolved the issue. The reason was that I initially installed pyopengl==3.1.5 according to the environment.yml file and then installed bop_toolbox. However, the latter requires pyopengl version 3.1.0, which led to the overwrite of the initially correct version. Thanks again for your great work.
